### ISSUE TITLE
Laravel7.28.4 无法安装。

### ISSUE THREAD

**Issue by ChenRuihua** [overtrue/laravel-easy-sms#2]
提示如下：
 [InvalidArgumentException]                                                                                                                                                                                                
  Could not find a matching version of package overtrue/laravel-easy-sms. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (dev).  

packagist里也搜不到。
![Snip20210103_2](https://user-images.githubusercontent.com/46486133/103472535-a6f87c80-4dc9-11eb-9795-ca807ea7029a.png)

**Comment by overtrue** [comment]
https://packagist.org/packages/overtrue/laravel-easy-sms
