### ISSUE TITLE
composer require overtrue/laravel-easy-sms 无法安装，还未发布

### ISSUE THREAD

**Issue by hihuangwei** [overtrue/laravel-easy-sms#3]

**Comment by overtrue** [comment]
https://packagist.org/packages/overtrue/laravel-easy-sms

**Comment by hihuangwei** [comment]
@overtrue 新版本还未发布

**Comment by overtrue** [comment]
https://github.com/overtrue/laravel-easy-sms/releases/tag/2.0.1
